/**
 * The extension's icon contract. Keep the Remix Icon dependency isolated here
 * so screens only depend on the small set of icons they actually use.
 */
export {
	RiArrowRightUpLine as ExternalLinkIcon,
	RiBugLine as DiagnosticsIcon,
	RiComputerLine as MonitorIcon,
	RiDashboardLine as ToolbarIcon,
	RiDatabase2Line as DatabaseIcon,
	RiDownloadLine as DownloadIcon,
	RiEqualizerLine as SlidersIcon,
	RiEyeOffLine as EyeOffIcon,
	RiFilter3Fill as FilterFillIcon,
	RiFilter3Line as FilterIcon,
	RiInformationFill as InformationFillIcon,
	RiInformationLine as InformationIcon,
	RiLayoutFill as LayoutFillIcon,
	RiLayoutLine as LayoutIcon,
	RiListSettingsFill as ListFilterFillIcon,
	RiListSettingsLine as ListFilterIcon,
	RiLoader4Line as LoaderIcon,
	RiMoonLine as MoonIcon,
	RiPaletteLine as AppearanceIcon,
	RiRefreshLine as RefreshIcon,
	RiSearchLine as SearchIcon,
	RiSettings3Fill as SettingsFillIcon,
	RiSettings3Line as SettingsIcon,
	RiShieldCheckLine as ShieldCheckIcon,
	RiSunLine as SunIcon,
	RiTwitterFill as TwitterIcon,
	RiTwitterXFill as XFillIcon,
	RiTwitterXLine as XIcon,
	RiUploadLine as UploadIcon,
	RiUser3Fill as UsersFillIcon,
	RiUser3Line as UsersIcon,
	RiUserForbidLine as UserSlashIcon,
	RiUserSettingsLine as AccountFilterIcon,
} from "@remixicon/react";
